import { type EmailOtpType } from '@supabase/supabase-js'
import { type NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

export async function GET(request: NextRequest) {
    const { searchParams } = new URL(request.url)
    const token_hash = searchParams.get('token_hash')
    const type = searchParams.get('type') as EmailOtpType | null
    const next = searchParams.get('next') ?? '/dashboard'

    // Note: Supabase currently recommends using token_hash over token.
    // The url generated by email templates usually is /auth/confirm?token_hash=...&type=signup

    if (token_hash && type) {
        const supabase = createClient()

        console.log(`[AUTH CONFIRM] Verificando OTP para o tipo: ${type}`)
        const { error } = await supabase.auth.verifyOtp({
            type,
            token_hash,
        })

        if (!error) {
            console.log('[AUTH CONFIRM] Email confirmado com sucesso! Redirecionando para login com success flag...')
            // redirect to login with confirmed flag so the user knows they can login
            const redirectUrl = request.nextUrl.clone()
            redirectUrl.pathname = '/login'
            redirectUrl.searchParams.set('confirmed', 'true')
            redirectUrl.searchParams.delete('token_hash')
            redirectUrl.searchParams.delete('type')
            return NextResponse.redirect(redirectUrl)
        } else {
            console.error('[AUTH CONFIRM] Erro ao verificar OTP:', error.message)
        }
    }

    // return the user to an error page with some instructions
    console.log('[AUTH CONFIRM] Token/Type inválidos ou expirados. Redirecionando para login com erro...')
    const errorUrl = request.nextUrl.clone()
    errorUrl.pathname = '/login'
    errorUrl.searchParams.set('error', 'invalid_token')
    errorUrl.searchParams.delete('token_hash')
    errorUrl.searchParams.delete('type')
    return NextResponse.redirect(errorUrl)
}
